services:
  pfs:
    build:
      context: .
    image: pfs:latest
    container_name: pfs
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - pfs-data:/data

volumes:
  pfs-data:
